# -*- coding: utf-8 -*-
"""ai_dashboard_li

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fY6Q-LIONa_FCBTY9BSyUiv_E_0dFWv3

# Welcome to Colab!
"""

import pandas as pd

df = pd.read_csv("/content/cleaned_group_death_claims.csv")
df.head()

df.shape
df.info()
df.describe()

df.isnull().sum()

df.fillna(df.median(numeric_only=True), inplace=True)

df.drop_duplicates(inplace=True)

df.drop(['Policy_ID'], axis=1, inplace=True, errors='ignore')

import matplotlib.pyplot as plt

df['claims_paid_amt'].hist()
plt.title("Claims Paid Amount Distribution")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.kdeplot(data=df, x="claims_paid_amt", fill=True)
plt.title("Distribution of Claims Paid Amount")
plt.xlabel("Claims Paid Amount")
plt.ylabel("Density")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load a fresh DataFrame to plot with the original 'life_insurer' column
df_original = pd.read_csv("/content/cleaned_group_death_claims.csv")

sns.boxplot(data=df_original, x="life_insurer", y="claims_paid_amt")
plt.title("Claims Paid Amount by Life Insurer")
plt.xticks(rotation=90)
plt.show()

sns.scatterplot(data=df, x="claims_pending_start_no", y="claims_paid_amt", alpha=0.5)

# Add trend line
import numpy as np
x = df['claims_pending_start_no']
y = df['claims_paid_amt']
m, b = np.polyfit(x, y, 1)
plt.plot(x, m*x + b, color='red') # Added color for better visibility

plt.title("Claims Pending Start Number vs Claims Paid Amount")
plt.xlabel("Claims Pending Start Number") # Added x-axis label
plt.ylabel("Claims Paid Amount") # Added y-axis label
plt.show()

sns.boxplot(data=df_original, x="category", y="claims_paid_amt")
plt.xticks(rotation=45)
plt.title("Claims Paid Amount by Category")
plt.show()

sns.countplot(data=df_original, x="category")
plt.title("Category Distribution")
plt.show()

sns.boxplot(data=df, x="High_Claim", y="claims_paid_amt")
plt.title("Claims Paid Amount Distribution by Claim Category")
plt.show()

import numpy as np

corr = df.select_dtypes(include=np.number).corr()

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

sns.pairplot(df[['claims_pending_start_amt','claims_paid_amt','claims_intimated_amt','High_Claim']],
             hue='High_Claim')
plt.show()

sns.scatterplot(data=df, x="claims_intimated_amt", y="claims_paid_amt", alpha=0.5)
plt.title("Claims Paid Amount vs Claims Intimated Amount")
plt.show()

claim_rate = df_original.groupby('category')['claims_paid_ratio_no'].mean()

claim_rate.plot(kind='barh')
plt.title("Claim Approval Rate by Policy Type")
plt.show()

df = pd.get_dummies(df, drop_first=True)

df['High_Claim'] = (df['claims_paid_amt'] > df['claims_paid_amt'].median()).astype(int)
X = df.drop('High_Claim', axis=1)
y = df['High_Claim']

X = df.drop('High_Claim', axis=1)
y = df['High_Claim']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1 Score:", f1_score(y_test, y_pred_rf))

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

ConfusionMatrixDisplay.from_estimator(rf, X_test, y_test)
plt.show()

import numpy as np

importances = rf.feature_importances_
features = X.columns

indices = np.argsort(importances)

plt.figure(figsize=(8,6))
plt.barh(range(len(indices)), importances[indices])
plt.yticks(range(len(indices)), [features[i] for i in indices])
plt.title("Feature Importance")
plt.xlabel("Importance")
plt.show()